### ISSUE TITLE
Error running splatplan

### ISSUE THREAD

**Issue by Logic530** [Victrid/splatplost#23]
```
(venv) root@logic-VirtualBox /h/l/splatplost# 
splatplan -i post.png -o post.order
Traceback (most recent call last):
  File "/home/logic/splatplost/venv/bin/splatplan", line 9, in <module>
    from splatplost.generate_route import ResetPosition, divide_image, generate_block_visit, generate_order_file, find_nearest_reset_position, \
  File "/home/logic/splatplost/venv/lib/python3.8/site-packages/splatplost/generate_route.py", line 98, in <module>
    def get_label(image: np.ndarray) -> tuple[np.ndarray, int]:
TypeError: 'type' object is not subscriptable
```

**Comment by Logic530** [comment]
```
(venv) root@logic-VirtualBox /h/l/splatplost [0|1]# pip show splatplost
Name: splatplost
Version: 0.1.4
Summary: A software-based SplatPost plotter.
Home-page: https://github.com/Victrid/splatplost
Author: Weihao Jiang
Author-email: weihau.chiang@gmail.com
License: GPLv3
Location: /home/logic/splatplost/venv/lib/python3.8/site-packages
Requires: Pillow, libnxctrl, tsp-solver2, scikit-image, setuptools, tqdm, numpy, scipy
Required-by: 
```

**Comment by Logic530** [comment]
```
(venv) root@logic-VirtualBox /h/l/splatplost# pip list
Package            Version  
------------------ ---------
aioconsole         0.5.1    
bidict             0.22.0   
blessed            1.17.10  
cffi               1.15.1   
click              8.1.3    
cryptography       3.3.2    
dbus-python        1.2.16   
dnspython          1.16.0   
evdev              1.6.0    
eventlet           0.31.0   
Flask              1.1.2    
Flask-SocketIO     5.0.1    
greenlet           1.1.3    
hid                1.0.5    
imageio            2.21.2   
importlib-metadata 4.12.0   
itsdangerous       2.1.2    
Jinja2             3.1.2    
libnxctrl          0.1.7    
MarkupSafe         2.1.1    
networkx           2.8.6    
numpy              1.23.2   
nxbt               0.1.4    
packaging          21.3     
Pillow             9.2.0    
pip                20.0.2   
pkg-resources      0.0.0    
psutil             5.6.6    
pycparser          2.21     
pynput             1.7.1    
pyparsing          3.0.9    
python-engineio    4.3.4    
python-socketio    5.7.1    
python-xlib        0.31     
PyWavelets         1.3.0    
scikit-image       0.19.3   
scipy              1.9.1    
setuptools         65.3.0   
six                1.16.0   
splatplost         0.1.4    
tifffile           2022.8.12
tqdm               4.64.0   
tsp-solver2        0.4.1    
wcwidth            0.2.5    
Werkzeug           2.2.2    
wheel              0.37.1   
zipp               3.8.1    
```

**Comment by Victrid** [comment]
This is python version problem. I'm working on build a flashable image to solve the python, and VM problem and it already ready for testing.

**Comment by Victrid** [comment]
Hello,

I've created an image allowing you to reboot into. It has all dependencies configured and easy to use.

[Use image](https://github.com/Victrid/splatplost/blob/master/docs/image.md)
[Use image zh-CN](https://github.com/Victrid/splatplost/blob/master/docs/image.zh-CN.md)
