### ISSUE TITLE
Bluetooth to switch connection failing on dev4

### ISSUE THREAD

**Issue by Zhetadelta** [Victrid/splatplost#48]
## Describe the bug

When attempting to connect to my switch using the Remote option, I get a OSError: unsupported XML-RPC protocol. This may be due to a blank Remote Server box, but I'm not sure what to put in that box. 

## Running Environment Information

**Splatplost version**: `0.2.0.dev3`

**Python version**: `3.10.6 (main, Aug 10 2022, 11:40:04) [GCC 11.3.0]`

**OS Information**: `Linux-5.15.0-48-generic-x86_64-with-glibc2.35`

**Systemd Version**: 

```
systemd 249 (249.11-0ubuntu3.4)
+PAM +AUDIT +SELINUX +APPARMOR +IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP -LIBFDISK +PCRE2 -PWQUALITY -P11KIT -QRENCODE +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified

```

**Python Traceback**

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/splatplost/gui/plotter.py", line 44, in run
    self.working_function()
  File "/usr/local/lib/python3.10/dist-packages/splatplost/gui/plotter.py", line 118, in pairing
    raise e
  File "/usr/local/lib/python3.10/dist-packages/splatplost/gui/plotter.py", line 113, in pairing
    connection = backend(**parameters)
  File "/usr/local/lib/python3.10/dist-packages/libnxctrl/rpc.py", line 61, in __init__
    self.control = ServerProxy(self.host)
  File "/usr/lib/python3.10/xmlrpc/client.py", line 1432, in __init__
    raise OSError("unsupported XML-RPC protocol")
OSError: unsupported XML-RPC protocol

```

**Bluetooth status**

```
● bluetooth.service - Bluetooth service
     Loaded: loaded (/lib/systemd/system/bluetooth.service; enabled; vendor preset: enabled)
     Active: active (running) since Sun 2022-10-09 14:52:25 EDT; 1h 5min ago
       Docs: man:bluetoothd(8)
   Main PID: 656 (bluetoothd)
     Status: "Running"
      Tasks: 1 (limit: 9312)
     Memory: 2.0M
        CPU: 4.848s
     CGroup: /system.slice/bluetooth.service
             └─656 /usr/lib/bluetooth/bluetoothd

Oct 09 15:34:11 Ichaival-r02-prime bluetoothd[656]: Endpoint unregistered: sender=:1.37 path=/MediaEndpoint/A2DPSink/sbc_xq_552
Oct 09 15:34:11 Ichaival-r02-prime bluetoothd[656]: Endpoint unregistered: sender=:1.37 path=/MediaEndpoint/A2DPSource/sbc_xq_552
Oct 09 15:34:17 Ichaival-r02-prime bluetoothd[656]: Endpoint registered: sender=:1.37 path=/MediaEndpoint/A2DPSink/sbc
Oct 09 15:34:17 Ichaival-r02-prime bluetoothd[656]: Endpoint registered: sender=:1.37 path=/MediaEndpoint/A2DPSource/sbc
Oct 09 15:34:17 Ichaival-r02-prime bluetoothd[656]: Endpoint registered: sender=:1.37 path=/MediaEndpoint/A2DPSink/sbc_xq_453
Oct 09 15:34:17 Ichaival-r02-prime bluetoothd[656]: Endpoint registered: sender=:1.37 path=/MediaEndpoint/A2DPSource/sbc_xq_453
Oct 09 15:34:17 Ichaival-r02-prime bluetoothd[656]: Endpoint registered: sender=:1.37 path=/MediaEndpoint/A2DPSink/sbc_xq_512
Oct 09 15:34:17 Ichaival-r02-prime bluetoothd[656]: Endpoint registered: sender=:1.37 path=/MediaEndpoint/A2DPSource/sbc_xq_512
Oct 09 15:34:17 Ichaival-r02-prime bluetoothd[656]: Endpoint registered: sender=:1.37 path=/MediaEndpoint/A2DPSink/sbc_xq_552
Oct 09 15:34:17 Ichaival-r02-prime bluetoothd[656]: Endpoint registered: sender=:1.37 path=/MediaEndpoint/A2DPSource/sbc_xq_552

```

**Comment by baconsaur** [comment]
I had this issue too, and the problem was that "remote" isn't the right option. For bluetooth, you want "nxbt". For me, that option wasn't showing up in the list because of a problem importing pynput while running with sudo. I fixed it by running `xhost +` first before starting splatplost. I hope that helps!

**Comment by revolutionchao** [comment]
> I had this issue too, and the problem was that "remote" isn't the right option. For bluetooth, you want "nxbt". For me, that option wasn't showing up in the list because of a problem importing pynput while running with sudo. I fixed it by running `xhost +` first before starting splatplost. I hope that helps!

I'm having a similar issue. Made a new linux partition on my laptop with a fresh install of mint (same OS as my desktop, which does and always has shown the nxbt option) as the bluetooth receiver is less sensitive to interference, and i've made sure it's activated, but have no nxbt option. can you give the exact command you used?

**Comment by Anna-Belles** [comment]
> > I had this issue too, and the problem was that "remote" isn't the right option. For bluetooth, you want "nxbt". For me, that option wasn't showing up in the list because of a problem importing pynput while running with sudo. I fixed it by running `xhost +` first before starting splatplost. I hope that helps!
> 
> I'm having a similar issue. Made a new linux partition on my laptop with a fresh install of mint (same OS as my desktop, which does and always has shown the nxbt option) as the bluetooth receiver is less sensitive to interference, and i've made sure it's activated, but have no nxbt option. can you give the exact command you used?

I am also having the same issue, I have never used linux/any coding language before. I typed 
`xhost +`, it then asks zsh: correct 'xhost' to 'host' [nyae]?
and after a y it says:
Host + not found: 2(SERVERFAIL)

any tips? I too am trying to get the GUI to actually be able to connect to the switch, by getting that nxbt option to show up, all i have are remote and Splatplost USB as optiojns.
(running via flashable image for context)
