### ISSUE TITLE
Showing Error when press Draw

### ISSUE THREAD

**Issue by kenny-wong** [Victrid/splatplost#55]
## Describe the bug

Using the latest version GUI to draw on Splatoon 3. Already paired with Switch and can press L/R button. Loaded PIC and try to select some area and draw.  It show error after press "Draw selected" button.

## Running Environment Information

**Splatplost version**: `0.2.0.dev4`

**Python version**: `3.10.6 (main, Aug  3 2022, 17:39:45) [GCC 12.1.1 20220730]`

**OS Information**: `Linux-5.19.6-arch1-1-x86_64-with-glibc2.36`

**Systemd Version**: 

```
systemd 251 (251.4-1-arch)
+PAM +AUDIT -SELINUX -APPARMOR -IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY +P11KIT -QRENCODE +TPM2 +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -BPF_FRAMEWORK +XKBCOMMON +UTMP -SYSVINIT default-hierarchy=unified

```

**Python Traceback**

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/splatplost/gui/plotter.py", line 46, in run
    self.working_function()
  File "/usr/lib/python3.10/site-packages/splatplost/gui/plotter.py", line 265, in draw_func
    partial_plot_with_conn(self.connection, self.RouteFile.blocks.items(), key_binding=self.current_key_binding,
  File "/usr/lib/python3.10/site-packages/splatplost/plot.py", line 317, in partial_plot_with_conn
    execute_command_list(command_list, connection, stable_mode=stable_mode)
  File "/usr/lib/python3.10/site-packages/splatplost/plot.py", line 99, in execute_command_list
    connection.button_hold(command[0], command[1])
  File "/usr/lib/python3.10/site-packages/libnxctrl/rpc.py", line 72, in button_hold
    self.control.button_hold(
  File "/usr/lib/python3.10/xmlrpc/client.py", line 1122, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python3.10/xmlrpc/client.py", line 1464, in __request
    response = self.__transport.request(
  File "/usr/lib/python3.10/xmlrpc/client.py", line 1166, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.10/xmlrpc/client.py", line 1182, in single_request
    return self.parse_response(resp)
  File "/usr/lib/python3.10/xmlrpc/client.py", line 1354, in parse_response
    return u.close()
  File "/usr/lib/python3.10/xmlrpc/client.py", line 668, in close
    raise Fault(**self._stack[0])
xmlrpc.client.Fault: <Fault 1: "<class 'TypeError'>:NXBTControl.button_hold() got an unexpected keyword argument 'button_name'">

```

**Bluetooth status**

```
● bluetooth.service - Bluetooth service
     Loaded: loaded (/usr/lib/systemd/system/bluetooth.service; enabled; preset: disabled)
    Drop-In: /run/systemd/system/bluetooth.service.d
             └─nxbt.conf
     Active: active (running) since Thu 2022-11-10 10:07:59 UTC; 33min ago
       Docs: man:bluetoothd(8)
   Main PID: 3525967 (bluetoothd)
     Status: "Running"
      Tasks: 1 (limit: 38079)
     Memory: 1.0M
        CPU: 609ms
     CGroup: /system.slice/bluetooth.service
             └─3525967 /usr/lib/bluetooth/bluetoothd --compat "--noplugin=*"

Nov 10 10:07:59 arch-splatplost-iso bluetoothd[3525967]: Excluding (cli) avrcp
Nov 10 10:07:59 arch-splatplost-iso bluetoothd[3525967]: Excluding (cli) network
Nov 10 10:07:59 arch-splatplost-iso bluetoothd[3525967]: Excluding (cli) input
Nov 10 10:07:59 arch-splatplost-iso bluetoothd[3525967]: Excluding (cli) hog
Nov 10 10:07:59 arch-splatplost-iso bluetoothd[3525967]: Excluding (cli) gap
Nov 10 10:07:59 arch-splatplost-iso bluetoothd[3525967]: Excluding (cli) scanparam
Nov 10 10:07:59 arch-splatplost-iso bluetoothd[3525967]: Excluding (cli) deviceinfo
Nov 10 10:07:59 arch-splatplost-iso bluetoothd[3525967]: Excluding (cli) midi
Nov 10 10:07:59 arch-splatplost-iso bluetoothd[3525967]: Excluding (cli) battery
Nov 10 10:07:59 arch-splatplost-iso bluetoothd[3525967]: Bluetooth management interface 1.22 initialized

```

**Comment by kenny-wong** [comment]
![image](https://user-images.githubusercontent.com/6819339/201071798-ce433818-ce25-4841-950a-2f90d16bdaf1.png)

**Comment by kenny-wong** [comment]
Some warning during start up GUI
-----------------------------------------------------------------------
130 splatplost@arch-splatplost-iso ~/bin % sudo splatplost
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
/usr/lib/python3.10/site-packages/requests/__init__.py:102: RequestsDependencyWarning: urllib3 (1.26.12) or chardet (5.0.0)/charset_normalizer (2.0.12) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "
